# Generated by Django 5.0.1 on 2024-02-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="counted_views",
            field=models.IntegerField(default=0),
        ),
    ]
